Repository TGSAI/mdio-cpp, pull requests merged in 2024-08, with the labels that each got.

#66 Add collaboration information
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ContributionGuide.md
  README.md
Labels: documentation, enhancement

#64 Provide a CMake target for MDIO
  CMakeLists.txt
  cmake/FindEXT_TENSORSTORE.cmake
  cmake/Findnlohmann_json_schema_validator.cmake
  cmake/mdioConfig.cmake.in
  examples/hello_mdio/CMakeLists.txt
  examples/hello_mdio/src/hello_mdio.cc
  examples/hello_mdio/src/hello_mdio.h
  mdio/CMakeLists.txt
Labels: Improvement

#67 Added dataset model notation and static string for current version nu…
  mdio/dataset_schema.h
Labels: Improvement

#75 Add source directory guard for setting internal deps variable
  CMakeLists.txt
Labels: Improvement

#72 70 s3 unit tests
  CMakeLists.txt
  mdio/CMakeLists.txt
  mdio/s3_test.cc
Labels: enhancement

#86 Make contributing document link references unique.
  CONTRIBUTING.md
Labels: documentation

#76 Make mdio::utils::DeleteDataset more secure
  mdio/utils.h
Labels: Improvement

#84 83 json dne exception
  mdio/dataset.h
  mdio/dataset_test.cc
  mdio/dataset_validator.h
  mdio/variable.h
Labels: bug

#82 Fixes to CMake
  CMakeLists.txt
  mdio/CMakeLists.txt
Labels: Improvement

#71 Cleared TODO regarding segfaults and fixed re-publishing metadata behavior
  mdio/dataset.h
  mdio/utils.h
  mdio/variable.h
  mdio/variable_test.cc
Labels: bug

#73 Fix DevContainer Python deps and build speed
  .devcontainer/Dockerfile
Labels: CI/CD, Improvement

#93 91 stats json error
  mdio/stats.h
  mdio/stats_test.cc
Labels: bug

#94 Added methods to get the intervals of Variables and Datasets
  mdio/dataset.h
  mdio/dataset_test.cc
  mdio/variable.h
  mdio/variable_test.cc
Labels: enhancement

#92 User guide
  USER_GUIDE.md
Labels: documentation, help wanted

#100 95 isel expansion
  CMakeLists.txt
  mdio/CMakeLists.txt
  mdio/acceptance_test.cc
  mdio/dataset.h
  mdio/dataset_test.cc
  mdio/utils.h
  mdio/utils_test.cc
  mdio/variable.h
  mdio/variable_test.cc
Labels: enhancement
